"""Teste do Vetor Kanivete pela API real (app em --agente=9333): monta um cartão de visita pelos comandos (window.VKN),
Pathfinder, deslocar/contornar traço, separações e sobreimpressão, fechamento, PDF/X-4 e PDF/X-1a relidos e conferidos, PNG, salvar/reabrir .aknv, abrir PDF/SVG/PPTX e
desfazer. Sai com 1 se algo reprovar. Amostras em D:/kanivete_testes/vetor/amostras (geradas se faltarem).

    python testes/teste_vetor.py [--porta 9333] [--print saida.png]
"""
import argparse, json, os, subprocess, sys
sys.stdout.reconfigure(encoding="utf-8")
from playwright.sync_api import sync_playwright

RAIZ = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AM = r"D:\kanivete_testes\vetor\amostras"
SAI = r"D:\kanivete_testes\vetor\saida"
ap = argparse.ArgumentParser(); ap.add_argument("--porta", type=int, default=9333); ap.add_argument("--print", default=os.path.join(SAI, "tela.png"))
a = ap.parse_args()
os.makedirs(SAI, exist_ok=True)
if not os.path.isfile(os.path.join(AM, "apresentacao.pptx")):
    subprocess.run([sys.executable, os.path.join(r"D:\kanivete_testes\scripts", "gerar_amostras_vetor.py")], check=False)

falhas = []
def ok(cond, msg):
    print(("  ok  " if cond else "  FALHOU  ") + msg)
    if not cond: falhas.append(msg)

with sync_playwright() as p:
    b = p.chromium.connect_over_cdp(f"http://127.0.0.1:{a.porta}", timeout=20000)
    pg = next(x for c in b.contexts for x in c.pages if "index.html" in x.url)
    erros = []
    pg.on("console", lambda m: m.type == "error" and erros.append(m.text))
    pg.on("pageerror", lambda e: erros.append(str(e)))
    pg.evaluate("switchTool('vetor-kanivete')")
    pg.wait_for_function("window.VKN && document.getElementById('vk-canvas')", timeout=15000)
    C = lambda nome, args=None: pg.evaluate("([n, a]) => VKN.cmd(n, a)", [nome, args or {}])

    print("cartão 90×50 pelos comandos")
    r = C("novo", {"nome": "Cartao teste", "larg": 90, "alt": 50, "sangria": 3})
    ok(r["larg_mm"] == 90, "novo documento 90×50")
    fundo = C("retangulo", {"x": -3, "y": -3, "larg": 96, "alt": 56, "preench": "C100 M0 Y0 K0", "traco": "nenhum", "nome": "fundo"})
    t = C("texto", {"conteudo": "Vetor Kanivete", "x": 6, "y": 20, "fonte": "Arial", "estilo": "Bold", "tamanho": 16, "preench": "0K", "nome": "titulo"})
    ok(t["fonte_encontrada"] is True, "texto com Arial Bold (geometria do Python)")
    C("texto", {"conteudo": "contato@exemplo.com.br", "x": 6, "y": 40, "tamanho": 8, "preench": "C0 M0 Y0 K0", "nome": "contato"})
    e1 = C("elipse", {"x": 60, "y": 8, "larg": 20, "preench": "spot:PANTONE 1505 C:0,56,90,0", "traco": "nenhum"})
    e2 = C("estrela", {"cx": 78, "cy": 18, "raio": 9, "pontas": 5, "preench": "C0 M100 Y100 K0", "traco": "nenhum"})
    u = C("pathfinder", {"op": "unir", "ids": [e1["id"], e2["id"]]})
    ok(u["caixa_mm"]["larg"] > 20, f"Pathfinder unir ({u['caixa_mm']})")
    C("alterar", {"ids": [u["id"]], "preench": "spot:PANTONE 1505 C:0,56,90,0"})   # Unir fica com a cor do de cima (como no Illustrator)
    C("alinhar", {"ids": [t["id"]], "modo": "centro_h", "relativo": "prancheta"})
    cx = pg.evaluate("id => VKN.cmd('info', {ids: [id]})", t["id"])[0]["caixa_mm"]
    ok(abs(cx["x"] + cx["larg"] / 2 - 45) < 0.2, f"alinhado ao centro da prancheta ({cx})")
    C("linha", {"x1": 6, "y1": 30, "x2": 84, "y2": 30, "traco": "100K", "espessura": 0.1, "nome": "fio"})
    f = pg.evaluate("VKN.fechamento({padrao: 'x4'})")
    cods = [x["cod"] for x in f["erros"] + f["avisos"]]
    ok("traco_fino" in cods, "fechamento acusa traço de 0,1 pt")
    C("engrossar_tracos")
    f = pg.evaluate("VKN.fechamento({padrao: 'x4'})")
    ok(not f["erros"], f"fechamento sem erros depois de corrigir ({[x['msg'] for x in f['erros']]})")
    n_antes = pg.evaluate("vkTodos().length")
    C("duplicar", {"ids": [fundo["id"]]})
    pg.evaluate("vkDesfazer()")
    ok(pg.evaluate("vkTodos().length") == n_antes, "desfazer o duplicar")

    print("deslocar caminho e contornar traço")
    q = C("retangulo", {"x": 10, "y": 10, "larg": 20, "alt": 10, "preench": "C0 M0 Y100 K0", "traco": "100K", "espessura": 2, "nome": "selo"})
    d = C("deslocar", {"ids": [q["id"]], "distancia": 2, "junc": "round", "preench": "0K"})
    cx = pg.evaluate("id => VKN.cmd('info', {ids: [id]})", d["ids"][0])[0]["caixa_mm"]
    ok(abs(cx["larg"] - 24) < 0.6 and abs(cx["alt"] - 14) < 0.6, f"deslocar +2 mm (24×14 + traço: {cx})")
    di = C("deslocar", {"ids": [q["id"]], "distancia": -2})
    cx = pg.evaluate("id => VKN.cmd('info', {ids: [id]})", di["ids"][0])[0]["caixa_mm"]
    ok(abs(cx["larg"] - 16) < 0.6, f"deslocar −2 mm ({cx})")
    tr = C("contornar_traco", {"ids": [q["id"]]})
    o = pg.evaluate("id => vkObj(id)", tr["ids"][0])
    ok(o["tipo"] == "grupo" and len(o["itens"]) == 2 and o["itens"][1]["traco"] is None and o["itens"][1]["preench"]["v"] == [0, 0, 0, 100],
       "contornar traço: grupo [preenchimento, traço vira forma 100K]")
    tr2 = C("contornar_traco", {"ids": [C("linha", {"x1": 6, "y1": 46, "x2": 40, "y2": 46, "traco": "100K", "espessura": 2})["id"]]})
    o = pg.evaluate("id => vkObj(id)", tr2["ids"][0])
    ok(o["tipo"] == "caminho" and o["subs"] and o["subs"][0]["fechado"], "linha com traço vira forma fechada")
    C("apagar", {"ids": [*d["ids"], *di["ids"], *tr["ids"], *tr2["ids"]]})

    print("exportação")
    for padrao in ("x4", "x1a"):
        out = os.path.join(SAI, f"cartao_{padrao}.pdf")
        r = pg.evaluate("([c, p]) => VKN.exportarPdf(c, {padrao: p})", [out, padrao])
        ok(r["verificado"] and os.path.isfile(out), f"PDF/{padrao}: verificado={r['verificado']} {r['problemas']} cores={r['info']['cores']} spots={r['info']['spots']} v{r['info']['versao']}")
        ok("PANTONE 1505 C" in r["info"]["spots"], f"cor especial preservada no {padrao}")
    png = os.path.join(SAI, "cartao.png")
    r = pg.evaluate("c => VKN.exportarImagem(c, {ppi: 150})", png)
    ok(os.path.isfile(png) and os.path.getsize(png) > 2000, "PNG 150 ppi")
    aknv = os.path.join(SAI, "cartao.aknv")
    pg.evaluate("c => VKN.salvar(c)", aknv)
    n = pg.evaluate("vkTodos().length")
    pg.evaluate("c => VKN.abrir(c)", aknv)
    ok(pg.evaluate("vkTodos().length") == n, f"salvar e reabrir .aknv ({n} objetos)")
    pac = os.path.join(SAI, "pacote")
    import shutil; shutil.rmtree(pac, ignore_errors=True)
    r = pg.evaluate("c => VKN.empacotar(c)", pac)
    arqs = os.listdir(r["pasta"]) if os.path.isdir(r.get("pasta", "")) else []
    ok({"Relatório.txt", "Fontes"} <= set(arqs) and any(x.endswith(".aknv") for x in arqs) and r["pdf_verificado"],
       f"empacotar: {arqs} fontes={r['fontes']} pdf={r['pdf_verificado']}")

    print("abrir arquivos de fora")
    for arq, minimo in (("cmyk.pdf", 4), ("illustrator.svg", 6), ("apresentacao.pptx", 4)):
        r = pg.evaluate("c => VKN.abrir(c)", os.path.join(AM, arq))
        ok(r["objetos"] >= minimo, f"{arq}: {r['objetos']} objetos, {r['pranchetas']} prancheta(s), relatório {r['relatorio'][:2]}")
    pg.evaluate("VKN.abrir(arguments[0])" if False else "c => VKN.abrir(c)", os.path.join(AM, "illustrator.svg"))
    r = C("converter_cmyk")
    ok(r["convertidas"] > 0 and pg.evaluate("VKN.fechamento({padrao:'x1a'}).erros.filter(e => e.cod === 'rgb').length") == 0, f"SVG RGB → CMYK ({r['convertidas']} cores)")

    print("construir formas")
    C("novo", {"nome": "Construir", "larg": 120, "alt": 80})
    n_obj = lambda: pg.evaluate("vkTodos().length")
    a1 = C("elipse", {"x": 10, "y": 10, "larg": 30, "preench": "C100 M0 Y0 K0", "traco": "nenhum"})
    a2 = C("elipse", {"x": 30, "y": 10, "larg": 30, "preench": "C0 M100 Y0 K0", "traco": "nenhum"})
    r = C("construtor", {"ids": [a1["id"], a2["id"]], "juntar": [[20, 25], [35, 25]]})
    ok(r["regioes"] == 3 and r["juntadas"] == 2 and len(r["ids"]) == 2, f"construtor: 3 regiões, juntou 2 ({r})")
    pg.evaluate("vkDesfazer()")
    r = C("construtor", {"ids": [a1["id"], a2["id"]], "apagar": [[35, 25]]})
    ok(r["apagadas"] == 1 and len(r["ids"]) == 2, f"construtor com Alt apaga a interseção ({r})")
    pg.evaluate("vkDesfazer()")
    r = C("pathfinder2", {"ids": [a1["id"], a2["id"]], "op": "dividir"})
    ok(r["pecas"] == 3, f"Pathfinder Dividir em 3 ({r})")
    pg.evaluate("vkDesfazer()")
    r = C("pathfinder2", {"ids": [a1["id"], a2["id"]], "op": "menos_fundo"})
    ok(r["pecas"] == 1, f"Menos fundo ({r})")
    pg.evaluate("vkDesfazer()")
    q = C("retangulo", {"x": 70, "y": 10, "larg": 30, "alt": 20, "preench": "C0 M0 Y100 K0", "traco": "100K"})
    r = C("faca", {"linha": [[65, 20], [105, 20]], "ids": [q["id"]]})
    ok(r["cortados"] == 1 and r["pecas"] == 2, f"faca corta o retângulo em 2 ({r})")
    c = C("elipse", {"x": 10, "y": 45, "larg": 20, "preench": "nenhum", "traco": "100K", "espessura": 1})
    r = C("tesoura", {"x": 30, "y": 55})
    o = pg.evaluate("id => vkObj(id)", c["id"])
    ok(not o["subs"][0]["fechado"], "tesoura abre o círculo no ponto")
    l1 = C("linha", {"x1": 40, "y1": 50, "x2": 60, "y2": 50, "traco": "100K"})
    l2 = C("linha", {"x1": 62, "y1": 52, "x2": 80, "y2": 60, "traco": "100K"})
    r = C("juntar", {"ids": [l1["id"], l2["id"]]})
    ok(r.get("juntado") and r["pontos"] == 4 and n_obj() == pg.evaluate("vkTodos().length"), f"juntar 2 linhas ({r})")
    r = C("juntar", {"ids": [l1["id"]]})
    ok(r.get("fechado"), "juntar de novo fecha o caminho")

    print("transformar")
    C("novo", {"nome": "Transformar", "larg": 200, "alt": 100})
    cx = lambda i: pg.evaluate("id => VKN.cmd('info', {ids: [id]})", i)[0]["caixa_mm"]
    q = C("retangulo", {"x": 10, "y": 10, "larg": 8, "alt": 8, "preench": "C100 M0 Y0 K0", "traco": "nenhum"})
    C("duplicar", {"ids": [q["id"]], "dx": 12, "dy": 0})
    r = C("repetir", {"vezes": 3})
    ok(pg.evaluate("vkTodos().length") == 5 and abs(cx(r["ids"][0])["x"] - 58) < 0.01, f"passo e repetição: Ctrl+D x3 com cópia ({cx(r['ids'][0])})")
    e = C("elipse", {"x": 100, "y": 10, "larg": 6, "preench": "C0 M100 Y0 K0", "traco": "nenhum"})
    d = C("duplicar", {"ids": [e["id"]]})
    C("girar", {"ids": d["ids"], "graus": 30, "ox": 103, "oy": 40})
    C("repetir", {"vezes": 10})
    ok(pg.evaluate("vkTodos().length") == 17, f"girar cópia em volta de um ponto e repetir (12 bolinhas no círculo: {pg.evaluate('vkTodos().length') - 5})")
    a1 = C("retangulo", {"x": 10, "y": 40, "larg": 20, "alt": 10, "preench": "100K", "traco": "nenhum"})
    a2 = C("retangulo", {"x": 40, "y": 45, "larg": 30, "alt": 20, "preench": "100K", "traco": "nenhum"})
    C("transformar_cada", {"ids": [a1["id"], a2["id"]], "sx": 50, "sy": 50})
    b1, b2 = cx(a1["id"]), cx(a2["id"])
    ok(abs(b1["larg"] - 10) < 0.01 and abs(b1["x"] - 15) < 0.01 and abs(b2["larg"] - 15) < 0.01 and abs(b2["x"] - 47.5) < 0.01, f"transformar cada: 50% no próprio centro ({b1}, {b2})")
    a3 = C("retangulo", {"x": 80, "y": 60, "larg": 10, "alt": 10, "preench": "100K", "traco": "nenhum"})
    C("alinhar", {"ids": [a1["id"], a2["id"], a3["id"]], "modo": "topo", "relativo": "chave", "chave": a3["id"]})
    ok(abs(cx(a1["id"])["y"] - 60) < 0.01 and abs(cx(a3["id"])["y"] - 60) < 0.01, "alinhar ao objeto-chave (o chave não se move)")
    C("distribuir_espaco", {"ids": [a1["id"], a2["id"], a3["id"]], "eixo": "horizontal", "espaco": 5, "chave": a1["id"]})
    b1, b2, b3 = cx(a1["id"]), cx(a2["id"]), cx(a3["id"])
    ok(abs(b2["x"] - (b1["x"] + b1["larg"] + 5)) < 0.01 and abs(b3["x"] - (b2["x"] + b2["larg"] + 5)) < 0.01 and abs(b1["x"] - 15) < 0.01, f"distribuir espaçamento 5 mm a partir do chave ({b1['x']}, {b2['x']}, {b3['x']})")

    print("réguas, guias e grade")
    g = C("guia", {"eixo": "x", "pos": 50})
    C("guia", {"eixo": "y", "pos": 30})
    ok(pg.evaluate("VK.doc.guias.length") == 2 and abs(pg.evaluate("vkMM(VK.doc.guias[0].pos - VK.doc.pranchetas.find(p => p.id === VK.ativa).x)") - 50) < 0.01, "guias criadas em mm da prancheta")
    alvo_enc = pg.evaluate("() => { const o = vkTodos()[0].o, b = vkBox(o); const w = b[2] - b[0]; const r = vkEncaixe([VK.doc.guias[0].pos + 1, b[1], VK.doc.guias[0].pos + 1 + w, b[3]], new Set([o.id])); return r[0]; }")
    ok(abs(alvo_enc + 1) < 0.01, f"encaixa na guia ({alvo_enc})")
    r = C("exibir", {"grade": True, "encaixar_grade": True, "passo_grade": 10, "sub_grade": 2})
    ok(r["ativo"] and r["encaixar"], "grade ligada com encaixe")
    C("guia", {"acao": "limpar"}); C("exibir", {"grade": False, "encaixar_grade": False})
    ok(pg.evaluate("VK.doc.guias.length") == 0, "limpar guias")

    print("texto (caractere, parágrafo, encadear, caminho, estilos)")
    C("novo", {"nome": "Texto teste", "larg": 150, "alt": 100})
    I = lambda nome: C("info", {"nomes": [nome]})[0]
    G = lambda nome: pg.evaluate("n => { const o = vkTodos().find(x => x.o.nome === n).o; const g = vkGeo(o); return g && {partes: (g.partes || []).length, transborda: g.transborda, corte: g.corte, linhas: g.linhas.length, subs: g.subs.length}; }", nome)
    corpo = ("O KANIVETE faz arte para gráfica. " * 14).strip()
    C("texto", {"conteudo": corpo, "x": 10, "y": 10, "caixa": 50, "caixa_alt": 25, "tamanho": 10, "nome": "materia"})
    ok(G("materia")["transborda"], "caixa com altura fixa: texto sobrando (+ vermelho)")
    r = C("encadear", {"nomes": ["materia"], "nova": {"x": 70, "y": 10}})
    ok(r["caixas"] == 2, f"encadear numa caixa nova ({r})")
    seg = pg.evaluate("() => vkTodos().map(x => x.o).find(o => o.anterior)")
    ok(seg and seg["anterior"] and len(pg.evaluate("id => vkTxSpec(vkObj(id)).conteudo", seg["id"])) > 20, "o texto continua na 2ª caixa")
    C("alterar", {"nomes": ["materia"], "trecho": "KANIVETE", "estilo": "Bold", "preench": "C0 M100 Y0 K0"})
    inf = I("materia")
    ok(inf.get("trechos") and all(t["texto"] == "KANIVETE" for t in inf["trechos"]) and len(inf["trechos"]) == 14, f"estilo de caractere por trecho ({len(inf.get('trechos') or [])} trechos)")
    ok(G("materia")["partes"] == 2, "trecho colorido desenha em partes (tela = PDF)")
    C("alterar", {"nomes": ["materia"], "conteudo": "Novo: " + corpo})
    inf = I("materia")
    ok(all(t["texto"] == "KANIVETE" for t in inf["trechos"]), "editar o texto: os trechos acompanham")
    C("alterar", {"nomes": ["materia"], "recuo_1a": 12, "antes": 4, "alin": "just", "entrelinha": 13})
    ok(pg.evaluate("vkTodos().find(x => x.o.nome === 'materia').o.recuo_1a") == 12, "parágrafo: recuo da 1ª linha, espaço antes, justificado")
    r = C("estilo_texto", {"tipo": "paragrafo", "nome": "Corpo", "de": "materia", "aplicar": True})
    C("estilo_texto", {"tipo": "paragrafo", "nome": "Corpo", "tamanho": 9})
    ok(pg.evaluate("vkTodos().find(x => x.o.nome === 'materia').o.tam") == 9, "mudar o estilo de parágrafo atualiza o texto")
    C("estilo_texto", {"tipo": "caractere", "nome": "Destaque", "preench": "C100 M0 Y0 K0", "estilo": "Bold"})
    C("alterar", {"nomes": ["materia"], "trecho": "gráfica", "ocorrencia": 1, "estilo_caractere": "Destaque"})
    ok(any(t.get("ec") == "Destaque" for t in I("materia")["trechos"]), "estilo de caractere num trecho")
    C("texto", {"conteudo": "H2O e 1/2 kg, x2", "x": 10, "y": 60, "tamanho": 14, "nome": "quimica"})
    C("alterar", {"nomes": ["quimica"], "trecho": "2", "ocorrencia": 1, "pos": "sub"})
    C("alterar", {"nomes": ["quimica"], "frac": True})
    C("alterar", {"nomes": ["quimica"], "trecho": "x2", "maius": "versalete"})
    ok(G("quimica")["subs"] > 5, "subscrito, frações, versalete")
    C("elipse", {"x": 90, "y": 50, "larg": 40, "alt": 40, "nome": "circulo"})
    r = C("texto_caminho", {"nomes": ["circulo"], "conteudo": "TEXTO EM VOLTA DO CÍRCULO", "tamanho": 9, "nome": "volta"})
    g = G("volta")
    ok(g["subs"] > 10 and not g["transborda"] and r["caixa_mm"]["larg"] > 30, f"texto em caminho ({r['caixa_mm']})")
    sub_ = pg.evaluate("id => vkClone(vkObj(id).subs)", r["id"]); topo0_ = C("info", {"ids": [r["id"]]})[0]["caixa_mm"]["y"]
    sub_[0]["pts"][0][1] -= 30; sub_[0]["pts"][0][3] -= 30; sub_[0]["pts"][0][5] -= 30
    C("definir_subs", {"id": r["id"], "subs": sub_}); pg.evaluate("async id => await vkGeoPronta(vkObj(id))", r["id"])
    ok(C("info", {"ids": [r["id"]]})[0]["caixa_mm"]["y"] < topo0_ - 3, "editar a trilha (Seleção direta / definir_subs) refaz o texto em caminho")
    for i, (y, l) in enumerate([(80, "Primeira linha do"), (84.5, "parágrafo importado."), (93, "Outro parágrafo.")]):
        C("texto", {"conteudo": l, "x": 10, "y": y, "tamanho": 10, "nome": f"linha{i}"})
    r = C("juntar_textos", {"nomes": ["linha0", "linha1", "linha2"], "nome": "juntado"})
    ok(r["paragrafos"] == 2 and I("juntado")["conteudo"] == "Primeira linha do parágrafo importado.\nOutro parágrafo.", f"juntar textos linha a linha ({r})")
    gl = C("glifos", {"fonte": "Arial"})
    ok(len(gl["cars"]) > 200, f"glifos ({gl['total']})")
    C("inserir_texto", {"nomes": ["quimica"], "codigo": 0x2122})
    ok(I("quimica")["conteudo"].endswith("™"), "inserir glifo")
    out = os.path.join(SAI, "texto_x4.pdf")
    r = pg.evaluate("([c]) => VKN.exportarPdf(c, {padrao: 'x4', forcar: true})", [out])
    ok(r["verificado"] and r["info"]["fontes"] == 0, f"PDF/X-4 com trechos, encadeado e texto em caminho (verificado={r['verificado']} {r['problemas']})")
    r = C("desencadear", {"nomes": ["materia"]})
    ok(r["correntes"] == 1 and not pg.evaluate("vkTodos().some(x => x.o.anterior || x.o.seguinte)"), "desencadear: cada caixa fica com o seu texto")
    C("encadear", {"ids": [pg.evaluate("vkTodos().find(x => x.o.nome === 'materia').o.id"), seg["id"]]})
    C("apagar", {"nomes": ["materia"]})
    ok(pg.evaluate("id => { const o = vkObj(id); return !!o && !o.anterior && o.conteudo.startsWith('Novo:'); }", seg["id"]), "apagar a 1ª caixa: o texto passa para a seguinte")

    print("aparência e efeitos vivos")
    C("novo", {"nome": "Aparencia teste", "larg": 120, "alt": 80, "sangria": 3})
    P = lambda nome: pg.evaluate("async n => { const o = vkTodos().find(x => x.o.nome === n).o; const p = await vkApPronto(o); return p && p.map(x => ({pts: x.subs.reduce((s, b) => s + b.pts.length, 0), preench: !!x.preench, traco: x.traco ? x.traco.larg : null})); }", nome)
    C("retangulo", {"x": 5, "y": 5, "larg": 40, "alt": 25, "preench": "C0 M60 Y100 K0", "traco": "nenhum", "nome": "caixa"})
    C("efeito", {"nomes": ["caixa"], "tipo": "cantos", "raio": 4})
    ok(P("caixa")[0]["pts"] == 8, f"cantos arredondados vivos (4 cantos → 8 pontos: {P('caixa')})")
    C("texto", {"conteudo": "KANIVETE", "x": 55, "y": 25, "fonte": "Arial", "estilo": "Bold", "tamanho": 28, "preench": "0K", "nome": "logo"})
    C("aparencia", {"nomes": ["logo"], "tipo": "traco", "cor": "C0 M100 Y100 K0", "espessura": 6})
    C("aparencia", {"nomes": ["logo"], "tipo": "preench", "cor": "100K", "deslocar": 1.5})
    p = P("logo")
    ok(len(p) == 3 and p[0]["traco"] == 6 and p[1]["preench"] and p[2]["preench"], f"texto com 2 camadas de aparência atrás (traço 6 pt + preenchimento deslocado) ({[(x['preench'], x['traco']) for x in p]})")
    C("efeito", {"nomes": ["logo"], "tipo": "sombra", "dx": 1, "dy": 1, "desfoque": 1})
    C("elipse", {"x": 10, "y": 45, "larg": 25, "preench": "spot:PANTONE 286 C:100,75,0,0", "traco": "nenhum", "nome": "bola"})
    C("efeito", {"nomes": ["bola"], "tipo": "brilho", "cor": "spot:PANTONE 286 C:100,75,0,0", "desfoque": 2})
    C("estrela", {"cx": 60, "cy": 58, "raio": 12, "pontas": 5, "preench": "C0 M0 Y100 K0", "traco": "nenhum", "nome": "estrela"})
    C("efeito", {"nomes": ["estrela"], "tipo": "desfoque", "desfoque": 0.8})
    C("retangulo", {"x": 85, "y": 45, "larg": 12, "alt": 12, "preench": "C100 M0 Y0 K0", "traco": "nenhum", "nome": "q1"})
    C("retangulo", {"x": 99, "y": 45, "larg": 12, "alt": 12, "preench": "C0 M100 Y0 K0", "traco": "nenhum", "nome": "q2"})
    gq = C("agrupar", {"nomes": ["q1", "q2"], "nome": "grupo"})
    C("efeito", {"ids": [gq["id"]], "tipo": "sombra"})
    f = pg.evaluate("VKN.fechamento({padrao: 'x1a'})")
    ok("efeito_transparencia" in [x["cod"] for x in f["erros"]], "fechamento: efeito em PDF/X-1a é erro")
    out = os.path.join(SAI, "aparencia_x4.pdf")
    r = pg.evaluate("([c]) => VKN.exportarPdf(c, {padrao: 'x4'})", [out])
    ok(r["verificado"] and "PANTONE 286 C" in r["info"]["spots"], f"PDF/X-4 com aparência e efeitos (verificado={r['verificado']} {r['problemas']} spots={r['info']['spots']})")
    import pikepdf
    with pikepdf.open(out) as pdf:
        ims = [x for x in pdf.pages[0].Resources.XObject.values() if x.get("/SMask") is not None]
        css = sorted({str(x.ColorSpace[0]) if isinstance(x.ColorSpace, pikepdf.Array) else str(x.ColorSpace) for x in ims})
    ok(len(ims) == 4 and "/Separation" in css and "/DeviceCMYK" in css, f"efeitos rasterizados na cor da tinta, com máscara ({len(ims)} imagens, {css})")
    r = C("expandir_aparencia", {"nomes": ["logo"]})
    g = C("info", {"nomes": ["logo"]})[0]
    ok(r["expandidos"] == 1 and g["tipo"] == "grupo" and g["itens"] == 3 and g.get("efeitos") == ["sombra"], f"expandir aparência ({g.get('tipo')}, {g.get('itens')} itens, {g.get('efeitos')})")
    pg.evaluate("vkEnquadrar()"); pg.wait_for_timeout(600)
    pg.screenshot(path=os.path.join(SAI, "aparencia.png"))

    print("desenho à mão e traço (lápis, bolha, borracha, setas, perfil)")
    import math
    C("novo", {"nome": "Desenho teste", "larg": 120, "alt": 80})
    onda = [[5 + i * 2, 20 + 8 * math.sin(i / 3)] for i in range(40)]
    r = C("lapis", {"pontos": onda, "espessura": 1.5, "nome": "onda"})
    ok(4 <= r["pontos"] < 25 and not r["fechado"], f"lápis: 40 pontos viram curva suave ({r['pontos']} pontos)")
    import random; random.seed(7)
    tremida = [[10 + x / 2, 60 + 8 * math.sin(x / 2 / 40 * 2 * math.pi) + random.uniform(-0.35, 0.35)] for x in range(0, 160)]
    C("lapis", {"pontos": tremida, "nome": "tremida"})
    inf = pg.evaluate("""() => { const o = vkTodos().find(x => x.o.nome === 'tremida').o, pl = vkDsAmostrar(o.subs[0], 40); let n = 0, s0 = 0; const cs = [];
        for (let i = 2; i < pl.length; i++) { const a = pl[i-2], b = pl[i-1], c = pl[i]; cs.push((b[0]-a[0])*(c[1]-b[1]) - (b[1]-a[1])*(c[0]-b[0])); }
        const lim = Math.max(...cs.map(Math.abs)) * 0.05; for (const c of cs) { if (Math.abs(c) < lim) continue; const s = Math.sign(c); if (s0 && s !== s0) n++; s0 = s; } return [n, o.subs[0].pts.length]; }""")
    ok(inf[0] <= 4, f"lápis tira o tremido da mão (onda com ruído ±0,35 mm: {inf[0]} inflexões, {inf[1]} pontos)")
    roda = [[60 + 10 * math.cos(i / 20 * 2 * math.pi), 20 + 10 * math.sin(i / 20 * 2 * math.pi)] for i in range(21)]
    r = C("lapis", {"pontos": roda, "nome": "roda"})
    bx = C("info", {"nomes": ["roda"]})[0]["caixa_mm"]
    ok(r["fechado"] and r["pontos"] >= 4 and abs(bx["larg"] - 20) < 1, f"lápis fecha sozinho quando termina no começo ({r['pontos']} pontos, {bx})")
    pl = [[90 + 10 * math.cos(i / 100 * 2 * math.pi), 20 + 10 * math.sin(i / 100 * 2 * math.pi)] for i in range(100)]
    C("caminho", {"d": "M" + " L".join(f"{x:.3f} {y:.3f}" for x, y in pl) + " Z", "preench": "C0 M100 Y0 K0", "nome": "poligonao"})
    r = C("simplificar", {"nomes": ["poligonao"], "tolerancia": 0.1})
    bx = C("info", {"nomes": ["poligonao"]})[0]["caixa_mm"]
    ok(4 <= r["pontos_depois"] < r["pontos_antes"] / 3 and abs(bx["larg"] - 20) < 0.5 and abs(bx["alt"] - 20) < 0.5, f"simplificar: menos pontos, mesma forma ({r}, {bx})")
    C("linha", {"x1": 5, "y1": 45, "x2": 50, "y2": 45, "traco": "100K", "espessura": 3, "nome": "seta"})
    C("alterar", {"nomes": ["seta"], "perfil": "lente", "seta_fim": "triangulo", "seta_ini": "circulo"})
    p = P("seta")
    ok(len(p) == 2 and p[0]["preench"] and p[1]["preench"], f"perfil de largura + setas viram formas ({p})")
    C("bolha", {"pontos": [[60, 45], [80, 45]], "espessura": 4, "cor": "C100 M0 Y0 K0"})
    r = C("bolha", {"pontos": [[70, 40], [70, 55]], "espessura": 4, "cor": "C100 M0 Y0 K0"})
    ok(r["juntou"] == 1, "pincel de bolha junta com a forma da mesma cor que encosta")
    C("retangulo", {"x": 85, "y": 40, "larg": 30, "alt": 20, "preench": "C0 M0 Y100 K0", "traco": "nenhum", "nome": "amarelo"})
    C("selecionar", {"nomes": ["amarelo"]})
    r = C("borracha", {"pontos": [[100, 35], [100, 65]], "espessura": 3})
    n_subs = pg.evaluate("vkTodos().find(x => x.o.nome === 'amarelo').o.subs.length")
    ok(r["recortados"] == 1 and n_subs == 2, f"borracha corta o retângulo em dois ({r}, {n_subs} partes)")
    out = os.path.join(SAI, "desenho_x4.pdf")
    r = pg.evaluate("([c]) => VKN.exportarPdf(c, {padrao: 'x4'})", [out])
    ok(r["verificado"], f"PDF/X-4 com perfil e setas ({r['problemas']})")

    print("formas e recursos do desafio do flyer (arco, setor, QR, ícone, hifenização, repetir)")
    C("novo", {"nome": "Formas teste", "larg": 120, "alt": 80})
    r = C("caminho", {"d": "M10 20 A10 10 0 0 1 30 20 Z", "preench": "C0 M100 Y0 K0", "nome": "meia lua"})
    ok(abs(r["caixa_mm"]["larg"] - 20) < 0.05 and abs(r["caixa_mm"]["alt"] - 10) < 0.05, f"caminho com arco SVG (A) ({r['caixa_mm']})")
    r = C("setor", {"cx": 60, "cy": 40, "raio": 20, "de": -90, "ate": 0, "nome": "quarto"})
    ok(abs(r["caixa_mm"]["larg"] - 20) < 0.05 and abs(r["caixa_mm"]["x"] - 60) < 0.05, f"setor de 90° ({r['caixa_mm']})")
    r = C("setor", {"cx": 60, "cy": 40, "raio": 20, "raio_interno": 12, "de": 0, "ate": 180, "vao": 2, "nome": "rosca"})
    ok(r and r["caixa_mm"]["alt"] < 20, f"setor de rosca com vão ({r['caixa_mm']})")
    r = C("qrcode", {"conteudo": "https://kanivete.app", "x": 90, "y": 5, "tamanho": 20})
    ok(r["modulos"] >= 21 and abs(r["caixa_mm"]["larg"] - 20) < 0.05, f"QR code vetorial ({r['modulos']} módulos, {r['modulo_mm']} mm)")
    try:
        r = C("icone", {"nome": "trophy", "x": 5, "y": 50, "tamanho": 12, "cor": "C78 M0 Y95 K0"})
        ok(abs(r["caixa_mm"]["larg"] - 10) < 2.5 and r["licenca"].startswith("Tabler"), f"ícone Tabler ({r['caixa_mm']})")
    except Exception as e:
        print("  (ícone pulado: sem internet?)", str(e)[:80])
    t = C("texto", {"conteudo": "Some extraordinarily comprehensive internationalization documentation explains everything", "x": 5, "y": 65,
                    "caixa": 30, "fonte": "Arial", "tamanho": 8, "alin": "just", "hifen": "en_US", "nome": "hifenizado"})
    nh = pg.evaluate("() => { const o = vkTodos().find(x => x.o.nome === 'hifenizado').o, g = vkGeo(o); return g.linhas.filter(l => /[a-z]/i.test(o.conteudo[l.fim - 1] || '') && o.conteudo[l.fim] && /[a-z]/i.test(o.conteudo[l.fim])).length; }")
    ok(nh >= 1, f"hifenização quebra palavra no fim da linha ({nh} linhas hifenizadas)")
    s = C("retangulo", {"x": 5, "y": 75, "larg": 1, "alt": 3, "preench": "100K", "traco": "nenhum"})
    c = C("duplicar", {"ids": [s["id"]], "dx": 2})
    r = C("repetir", {"vezes": 5, "ids": c["ids"]})
    ok(len(r.get("novos") or []) == 5, f"repetir devolve todas as cópias ({len(r.get('novos') or [])})")
    d = C("retangulo", {"x": 5, "y": 5, "larg": 30, "alt": 10, "nome": "degrade"})
    C("degrade", {"nomes": ["degrade"], "cores": ["C100 M0 Y0 K0", "C0 M100 Y0 K0", "0K"], "angulo": 90})
    g = pg.evaluate("vkTodos().find(x => x.o.nome === 'degrade').o.preench")
    ok(g["k"] == "grad" and len(g["paradas"]) == 3 and abs(g["a"][0] - g["b"][0]) < 0.01, "degradê por ângulo (90° = vertical)")
    m1 = C("elipse", {"x": 40, "y": 60, "larg": 8, "preench": "C100 M0 Y0 K0", "traco": "nenhum"})
    m2 = C("estrela", {"cx": 80, "cy": 70, "raio": 8, "pontas": 5, "preench": "C0 M100 Y0 K0", "traco": "nenhum"})
    r = C("mesclar", {"ids": [m1["id"], m2["id"]], "passos": 5, "vivo": False})
    g = C("info", {"ids": [r["id"]]})[0]
    meio = pg.evaluate("id => vkObj(id).itens[3].preench.v", r["id"])
    ok(g["itens"] == 7 and r["reamostrado"] and abs(meio[0] - 50) < 1 and abs(meio[1] - 50) < 1, f"mesclar círculo → estrela em 5 passos (cor do meio {meio})")
    from PIL import Image as _Im, ImageDraw as _Dr, ImageFont as _Ft, ImageFilter as _Fl
    logo = os.path.join(SAI, "logo_trace.jpg"); im_ = _Im.new("RGB", (800, 500), "white"); d_ = _Dr.Draw(im_)
    d_.ellipse((60, 60, 360, 360), fill=(220, 30, 40)); d_.ellipse((150, 150, 270, 270), fill="white"); d_.rectangle((420, 80, 740, 240), fill=(20, 90, 200))
    d_.text((80, 385), "LOGO", font=_Ft.truetype(os.path.join(os.environ.get("WINDIR", "C:/Windows"), "Fonts", "arialbd.ttf"), 90), fill=(30, 30, 30))
    im_.filter(_Fl.GaussianBlur(1.2)).save(logo, quality=70)
    li = C("imagem", {"arquivo": logo, "x": 0, "y": 0, "larg": 60})
    r = C("vetorizar", {"ids": [li["id"]], "cores": 6})
    subs = pg.evaluate("id => vkObj(id).itens.map(o => o.subs.length)", r["ids"][0])
    ok(r["cores"] == 3 and sorted(subs) == [1, 2, 6], f"vetorizar logo JPG: 3 cores, anel com furo, LOGO com os furos dos O ({subs})")
    subprocess.run([sys.executable, r"D:\kanivete_testes\vetor\cores\gerar_livros.py"], check=False, capture_output=True)
    pu = C("bibliotecas_cor")["pasta_usuario"]; os.makedirs(pu, exist_ok=True)
    import shutil
    for f_ in ("TESTE Solid Coated.acb", "marca.ase"): shutil.copy(os.path.join(r"D:\kanivete_testes\vetor\cores", f_), pu)
    libs = [b_["nome"] for b_ in C("bibliotecas_cor")["bibliotecas"]]
    ok("TESTE Solid Coated" in libs and "marca" in libs, f"bibliotecas de cor achadas na pasta do usuário ({libs})")
    q = C("retangulo", {"x": 40, "y": 5, "larg": 15, "alt": 10, "nome": "pantone"})
    r = C("cor_biblioteca", {"biblioteca": "TESTE Solid", "nome": "286", "ids": [q["id"]], "preench": True})
    pr = pg.evaluate("id => vkObj(id).preench", q["id"])
    ok(pr["k"] == "spot" and pr["nome"] == "TESTE 286 C" and pr["v"][0] > 80, f"cor do livro (.acb em Lab) vira especial com CMYK alternativo ({pr})")
    r = C("cor_biblioteca", {"biblioteca": "marca", "todas": True})
    ok(len(r["amostras"]) == 2, f"todas as cores do .ase viram amostras ({r['amostras']})")
    C("novo", {"nome": "Recolorir", "larg": 100, "alt": 60})
    a1 = C("retangulo", {"x": 5, "y": 5, "larg": 20, "alt": 10, "preench": "C100 M0 Y0 K0", "traco": "nenhum"})
    t1 = C("texto", {"conteudo": "Marca nova", "x": 5, "y": 30, "tamanho": 14, "preench": "100K"})
    C("alterar", {"ids": [t1["id"]], "trecho": "nova", "preench": "C100 M0 Y0 K0"})
    a2 = C("retangulo", {"x": 40, "y": 5, "larg": 20, "alt": 10, "traco": "nenhum"})
    C("degrade", {"ids": [a2["id"]], "cores": ["C100 M0 Y0 K0", "0K"]})
    cs = C("cores_arte", {"tudo": True})["cores"]
    ok(cs[0]["cor"].startswith("C100 M0 Y0 K0") and cs[0]["usos"] == 3, f"cores da arte, mais usada primeiro ({cs[:2]})")
    r = C("recolorir", {"tudo": True, "trocas": [{"de": "C100 M0 Y0 K0", "para": "spot:TESTE 286 C:94,78,0,0"}]})
    k_ = pg.evaluate("([a, t, b]) => [vkObj(a).preench.k, vkObj(t).trechos[0].preench.k, vkObj(b).preench.paradas[0].cor.k]", [a1["id"], t1["id"], a2["id"]])
    ok(r["trocadas"] == 3 and k_ == ["spot", "spot", "spot"], f"recolorir troca no preenchimento, no trecho do texto e na parada do degradê ({r}, {k_})")
    pc1 = C("elipse", {"x": 70, "y": 40, "larg": 4, "preench": "C100 M0 Y0 K0", "traco": "nenhum"})
    pc2 = C("estrela", {"cx": 80, "cy": 48, "raio": 2.5, "pontas": 5, "preench": "spot:PANTONE 1505 C:0,56,90,0", "traco": "nenhum"})
    r = C("criar_padrao", {"ids": [pc1["id"], pc2["id"]], "nome": "Bolinhas", "espaco": 2, "apagar_originais": True})
    pq = C("retangulo", {"x": 60, "y": 30, "larg": 30, "alt": 20, "traco": "nenhum"})
    C("padrao", {"ids": [pq["id"]], "nome": "Bolinhas", "escala": 70, "angulo": 20})
    ok(r["objetos"] == 2 and pg.evaluate("id => vkObj(id).preench.k", pq["id"]) == "pad", f"criar padrão e aplicar com escala/ângulo ({r})")
    v1 = C("elipse", {"x": 5, "y": 62, "larg": 6, "preench": "C100 M0 Y0 K0", "traco": "nenhum"})
    v2 = C("retangulo", {"x": 40, "y": 62, "larg": 6, "alt": 6, "preench": "C0 M100 Y0 K0", "traco": "nenhum"})
    rv = C("mesclar", {"ids": [v1["id"], v2["id"]], "passos": 3})
    meio_v = lambda: pg.evaluate("id => vkMesclaTodos(vkObj(id))[2].preench.v.map(Math.round)", rv["id"])
    antes_v = meio_v(); C("alterar", {"ids": [v1["id"]], "preench": "C0 M0 Y100 K0"}); depois_v = meio_v()
    ok(rv["vivo"] and antes_v != depois_v and depois_v[2] == 50, f"mesclagem viva: mudar a forma A refaz os passos ({antes_v} → {depois_v})")
    esp_ = C("caminho", {"d": "M5 75 C30 55 60 95 90 75", "traco": "100K", "preench": "nenhum", "nome": "espinha"})
    C("mescla", {"ids": [rv["id"]], "espinha": "espinha", "passos": 6})
    bx_ = C("info", {"ids": [rv["id"]]})[0]["caixa_mm"]
    ok(bx_["larg"] > 80, f"mesclagem segue a espinha ({bx_})")
    C("expandir_mescla", {"ids": [rv["id"]]})
    ok(C("info", {"ids": [rv["id"]]})[0]["itens"] == 8, "expandir mesclagem vira objetos comuns")
    out = os.path.join(SAI, "formas_x4.pdf")
    r = pg.evaluate("([c]) => VKN.exportarPdf(c, {padrao: 'x4'})", [out])
    import pikepdf
    with pikepdf.open(out) as pdf_: tem_pad = any("/Pattern" in pp_.Resources for pp_ in pdf_.pages)
    ok(tem_pad and "PANTONE 1505 C" in r["info"]["spots"], f"padrão sai como tiling pattern vetorial, com a cor especial da peça ({r['info']['spots']})")
    ok(r["verificado"] and "TESTE 286 C" in r["info"]["spots"], f"PDF/X-4 com setor, QR, ícone e cor do livro como especial ({r['problemas']}, {r['info']['spots']})")

    print("símbolos e EPS")
    C("novo", {"nome": "Simbolos", "larg": 100, "alt": 60})
    e_ = C("estrela", {"cx": 10, "cy": 10, "raio": 5, "pontas": 5, "preench": "C0 M100 Y0 K0", "traco": "nenhum"})
    r = C("criar_simbolo", {"ids": [e_["id"]], "nome": "Estrela"})
    for i_, (x_, esc_, ang_) in enumerate(((40, 100, 0), (60, 150, 30), (80, 60, 0))):
        C("colocar_simbolo", {"nome": "Estrela", "x": x_, "y": 30, "escala": esc_, "angulo": ang_})
    s_ = C("simbolos")["simbolos"][0]
    ok(s_["instancias"] == 4, f"símbolo com 4 instâncias ({s_})")
    larg_antes = C("info", {"ids": [r["instancia"]]})[0]["caixa_mm"]["larg"]
    nv = C("elipse", {"x": 0, "y": 45, "larg": 20, "alt": 6, "preench": "C100 M0 Y0 K0", "traco": "nenhum"})
    C("redefinir_simbolo", {"simbolo": "Estrela", "ids": [nv["id"]], "apagar_originais": True})
    larg_depois = C("info", {"ids": [r["instancia"]]})[0]["caixa_mm"]["larg"]
    ok(abs(larg_depois - 20) < 0.1 and abs(larg_antes - larg_depois) > 5, f"redefinir o símbolo muda todas as instâncias ({larg_antes} → {larg_depois} mm)")
    out_s = os.path.join(SAI, "simbolos_x4.pdf")
    r_ = pg.evaluate("([c]) => VKN.exportarPdf(c, {padrao: 'x4'})", [out_s])
    ok(r_["verificado"] and "CMYK" in r_["info"]["cores"], f"PDF com instâncias de símbolo ({r_['problemas']})")
    r_ = C("soltar_simbolo", {"ids": [r["instancia"]]})
    ok(r_["soltos"] == 1 and C("simbolos")["simbolos"][0]["instancias"] == 3, "soltar símbolo vira grupo comum")
    C("novo", {"nome": "Opmask", "larg": 80, "alt": 50})
    a_ = C("retangulo", {"x": 5, "y": 5, "larg": 60, "alt": 30, "preench": "C0 M100 Y0 K0", "traco": "nenhum"})
    m_ = C("retangulo", {"x": 5, "y": 5, "larg": 60, "alt": 30, "traco": "nenhum"})
    C("degrade", {"ids": [m_["id"]], "cores": ["0K", "100K"]})
    r_ = C("mascara_opacidade", {"ids": [a_["id"], m_["id"]]})
    out_m = os.path.join(SAI, "opmask_x4.pdf"); r2_ = pg.evaluate("([c]) => VKN.exportarPdf(c, {padrao: 'x4'})", [out_m])
    with pikepdf.open(out_m) as pdf_: tem_sm = any("/SMask" in g_ for pp_ in pdf_.pages for g_ in (pp_.Resources.get("/ExtGState") or {}).values())
    f_ = pg.evaluate("VKN.fechamento({padrao: 'x1a'})")
    ok(r_["arte"] == 1 and r2_["verificado"] and tem_sm and any(e["cod"] == "transparencia" for e in f_["erros"]), "máscara de opacidade: SMask de luminosidade no PDF/X-4, erro em X-1a")
    C("novo", {"nome": "Cardapio", "larg": 100, "alt": 60})
    tc_ = C("texto", {"conteudo": "Picanha\tR$ 89,90\nSuco\tR$ 9,50", "x": 5, "y": 5, "caixa": 80, "tamanho": 10, "fonte": "Arial", "tabs": "70 decimal .", "nome": "cardapio"})
    sem_ = C("texto", {"conteudo": "Picanha\tR$ 89,90\nSuco\tR$ 9,50", "x": 5, "y": 30, "caixa": 80, "tamanho": 10, "fonte": "Arial", "nome": "sem tabs"})
    n_ = pg.evaluate("() => ['cardapio', 'sem tabs'].map(n => { const o = vkTodos().find(x => x.o.nome === n).o, g = vkGeo(o); return g.subs.length; })")
    vg = pg.evaluate("() => { const g = vkGeo(vkTodos().find(x => x.o.nome === 'cardapio').o); return g.linhas.map(l => +(l.x + l.larg).toFixed(1)); }")
    ok(n_[0] > n_[1] + 20 and abs(vg[0] - vg[1]) < 0.5, f"tabulação decimal com pontilhado: vírgulas alinhadas e pontos ({n_}, fim das linhas {vg})")
    pg.evaluate("id => { VK.sel = [id]; vkTextoEditar(vkObj(id)); }", sem_["id"])
    pg.evaluate("() => { const ta = document.getElementById('vk-texto-edit'); ta.setSelectionRange(0, 0); ta.focus(); }")
    pg.keyboard.press("Tab"); pg.keyboard.press("Escape"); pg.wait_for_timeout(300)
    ok(pg.evaluate("id => vkObj(id).conteudo", sem_["id"]).startswith("\t"), "Tab na edição de texto insere tabulação")
    el_ = C("elipse", {"x": 5, "y": 30, "larg": 60, "alt": 28, "preench": "C0 M0 Y20 K0", "traco": "nenhum", "nome": "balao"})
    tf_ = C("texto_em_forma", {"ids": [el_["id"]], "conteudo": ("Texto que corre dentro da elipse como no Illustrator. " * 3).strip(), "tamanho": 7, "recuo": 1.5, "alin": "centro"})
    lg_ = pg.evaluate("id => vkGeo(vkObj(id)).linhas.map(l => +l.larg.toFixed(1))", tf_["id"])
    ok(tf_["linhas"] >= 4 and lg_[0] < max(lg_) * 0.8, f"texto dentro da forma: linhas acompanham a elipse ({lg_})")
    C("alterar", {"ids": [tf_["id"]], "tamanho": 14})
    ok(pg.evaluate("id => vkGeo(vkObj(id)).transborda", tf_["id"]), "texto que não cabe na forma acusa sobra (+ vermelho)")
    C("novo", {"nome": "Distorcer", "larg": 120, "alt": 60})
    pts_ = {}
    for tipo_, extra_ in (("zigue", {"tamanho": 2, "cristas": 4}), ("aspero", {"tamanho": 1}), ("inflar", {"quantidade": 60}), ("torcer", {"graus": 60}), ("brilho_interno", {"desfoque": 2})):
        q_ = C("estrela", {"cx": 15 + len(pts_) * 22, "cy": 30, "raio": 9, "pontas": 5, "preench": "C0 M100 Y0 K0", "traco": "nenhum"})
        C("efeito", {"ids": [q_["id"]], "tipo": tipo_, **extra_})
        pts_[tipo_] = pg.evaluate("async id => { const p = await vkApPronto(vkObj(id)); return p[0].subs[0].pts.length; }", q_["id"])
    ok(pts_["zigue"] > 30 and pts_["aspero"] > 10 and pts_["torcer"] >= 40 and pts_["brilho_interno"] == 10, f"efeitos de distorção vivos mudam a forma; brilho interno não ({pts_})")
    tt_ = C("texto", {"conteudo": "PROMOÇÃO", "x": 5, "y": 55, "fonte": "Arial", "estilo": "Black", "tamanho": 20, "preench": "C0 M100 Y100 K0"})
    alt0_ = pg.evaluate("async id => { const p = await vkApPronto(vkObj(id)); const b = [1e9, 1e9, -1e9, -1e9]; p.forEach(q => vkSubsBox(q.subs, null, b)); return b[1]; }", tt_["id"])
    C("efeito", {"ids": [tt_["id"]], "tipo": "deformar", "estilo": "arco", "dobra": 50})
    alt1_ = pg.evaluate("async id => { const p = await vkApPronto(vkObj(id)); const b = [1e9, 1e9, -1e9, -1e9]; p.forEach(q => vkSubsBox(q.subs, null, b)); return b[1]; }", tt_["id"])
    ok(alt1_ < alt0_ - 2, f"envelope em arco curva o texto vivo (topo {alt0_:.1f} → {alt1_:.1f} pt)")
    out_d = os.path.join(SAI, "distorcer.pdf"); r_ = pg.evaluate("([c]) => VKN.exportarPdf(c, {padrao: 'x4'})", [out_d])
    f_ = pg.evaluate("VKN.fechamento({padrao: 'x1a'})")
    ok(r_["verificado"] and sum(1 for e in f_["erros"] if e["cod"] == "efeito_transparencia") == 1, f"PDF com distorções; em X-1a só o brilho interno é transparência ({[e['cod'] for e in f_['erros']]})")
    C("novo", {"nome": "Cracha teste", "larg": 54, "alt": 86})
    C("texto", {"conteudo": "Nome", "x": 5, "y": 40, "tamanho": 14, "nome": "nome"})
    C("qrcode", {"conteudo": "x", "x": 15, "y": 50, "tamanho": 24, "nome": "qr"})
    csv_ = os.path.join(SAI, "equipe.csv"); open(csv_, "w", encoding="utf-8").write("nome;qr\nAna;https://exemplo.com/ana\nBruno;https://exemplo.com/bruno\n")
    out_md = os.path.join(SAI, "crachas.pdf"); r_ = C("mala_direta", {"csv": csv_, "saida": out_md})
    import fitz, numpy as np, cv2
    lidos_ = []
    for pp_ in fitz.open(out_md):
        px_ = pp_.get_pixmap(dpi=300); im_ = np.frombuffer(px_.samples, np.uint8).reshape(px_.height, px_.width, px_.n)[:, :, :3]
        lidos_.append(cv2.QRCodeDetector().detectAndDecode(cv2.cvtColor(im_, cv2.COLOR_RGB2BGR))[0])
    ok(r_["paginas"] == 2 and lidos_ == ["https://exemplo.com/ana", "https://exemplo.com/bruno"] and pg.evaluate("vkTodos().find(x => x.o.nome === 'nome').o.conteudo") == "Nome",
       f"mala direta: uma página por linha, QR de cada um lido no PDF, documento volta ao original ({r_['paginas']} páginas, {lidos_})")
    C("novo", {"nome": "Ampliar", "larg": 100, "alt": 100})
    fi_ = C("imagem", {"arquivo": "D:/kanivete_testes/flyer_webmart/f4.png", "x": 5, "y": 5, "larg": 80})
    cx0_ = C("info", {"ids": [fi_["id"]]})[0]["caixa_mm"]
    r_ = C("ampliar_imagem", {"ids": [fi_["id"]], "escala": 2})
    cx1_ = C("info", {"ids": [fi_["id"]]})[0]["caixa_mm"]
    ok(r_["ampliadas"][0]["ppi"] == 2 * r_["ampliadas"][0]["ppi_antes"] and cx0_ == cx1_, f"ampliar imagem por IA: ppi dobra, mesmo tamanho na página ({r_['ampliadas'][0]})")
    C("novo", {"nome": "Texto editavel", "larg": 100, "alt": 60})
    C("texto", {"conteudo": "Olá, gráfica! Texto copiável.", "x": 5, "y": 12, "fonte": "Arial", "tamanho": 12})
    C("texto", {"conteudo": "Some extraordinarily comprehensive internationalization documentation explains everything", "x": 5, "y": 20, "caixa": 30, "fonte": "Arial", "tamanho": 8, "alin": "just", "hifen": "en_US"})
    out_te = os.path.join(SAI, "texto_editavel.pdf"); r_ = pg.evaluate("([c]) => VKN.exportarPdf(c, {padrao: 'x4', texto_editavel: true})", [out_te])
    txt_ = fitz.open(out_te)[0].get_text()
    ok(r_["verificado"] and r_["info"]["fontes"] >= 1 and "Olá, gráfica! Texto copiável." in txt_ and "-" in txt_, f"PDF com texto editável: fonte embutida, texto copiável, hífen da hifenização ({r_['info']['fontes']} fontes)")
    C("novo", {"nome": "Malha teste", "larg": 80, "alt": 60})
    fm_ = C("elipse", {"x": 10, "y": 10, "larg": 50, "alt": 40, "preench": "C100 M60 Y0 K20", "traco": "nenhum"})
    pg.evaluate("vkEnquadrar(); vkDesenhar()"); pg.wait_for_timeout(300)
    tela_ = lambda x, y: pg.evaluate("([x, y]) => { const p = VK.doc.pranchetas[0], r = vkCanvas().getBoundingClientRect(), [sx, sy] = vkTela(p.x + vkPT(x), p.y + vkPT(y)); return [r.left + sx, r.top + sy]; }", [x, y])
    pg.keyboard.press("Escape"); pg.mouse.click(*tela_(75, 55)); pg.keyboard.press("u"); pg.mouse.click(*tela_(35, 30)); pg.wait_for_timeout(600)
    mid_ = pg.evaluate("vkTodos().map(x => x.o).find(o => o.tipo === 'malha').id")
    pg.evaluate("VK.preench = {k: 'cmyk', v: [0, 0, 100, 0]}")
    no_ = pg.evaluate("id => vkObj(id).nos[1][1]", mid_); pp_ = pg.evaluate("([x, y]) => { const r = vkCanvas().getBoundingClientRect(), [sx, sy] = vkTela(x, y); return [r.left + sx, r.top + sy]; }", no_)
    pg.mouse.click(*pp_); pg.wait_for_timeout(400)
    cor_ = pg.evaluate("id => vkObj(id).cores[1][1].v", mid_)
    out_mh = os.path.join(SAI, "malha.pdf"); r_ = pg.evaluate("([c]) => VKN.exportarPdf(c, {padrao: 'x1a'})", [out_mh])
    with pikepdf.open(out_mh) as pdf_: tipos_ = [int(x_.ShadingType) for pp2_ in pdf_.pages for x_ in (pp2_.Resources.get("/Shading") or {}).values()]
    ok(cor_ == [0, 0, 100, 0] and r_["verificado"] and 6 in tipos_, f"malha de degradê: ferramenta U cria e pinta o nó; PDF/X-1a com Coons mesh ({cor_}, shading {tipos_})")
    pg.keyboard.press("v")
    eps = os.path.join(SAI, "teste.eps"); open(eps, "w").write("%!PS-Adobe-3.0 EPSF-3.0\n%%BoundingBox: 0 0 100 100\n0 0 1 setrgbcolor 10 10 80 80 rectfill\nshowpage\n")
    try:
        r_ = C("abrir", {"caminho": eps}); ok(r_ and not r_.get("cancelado"), "EPS aberto pelo Ghostscript")
    except Exception as e_eps:
        ok("Ghostscript" in str(e_eps), "EPS sem Ghostscript: mensagem clara de como instalar")

    print("recuperação (salvamento automático)")
    C("recuperacao", {"acao": "descartar", "todos": True})
    C("novo", {"nome": "Recup A", "larg": 50, "alt": 50}); C("retangulo", {"x": 5, "y": 5, "larg": 10, "alt": 10})
    uid_a = pg.evaluate("vkUid()")
    C("novo", {"nome": "Recup B", "larg": 50, "alt": 50})   # A tinha alteração: vai para a recuperação sozinho
    ok(any(c_["uid"] == uid_a for c_ in C("recuperacao")["copias"]), "trocar de documento guarda a alteração não salva na recuperação")
    C("recuperacao", {"acao": "recuperar", "uid": uid_a})
    ok(pg.evaluate("VK.doc.nome") == "Recup A" and pg.evaluate("vkTodos().length") == 1, "recuperar devolve o documento")
    C("salvar", {"caminho": os.path.join(SAI, "recup_a.aknv")})
    ok(not any(c_["uid"] == uid_a for c_ in C("recuperacao")["copias"]), "salvar apaga a cópia de recuperação")

    print("separações e sobreimpressão")
    C("novo", {"nome": "Sep teste", "larg": 100, "alt": 60, "sangria": 3})
    C("retangulo", {"x": 0, "y": 0, "larg": 100, "alt": 60, "preench": "C0 M0 Y100 K0", "traco": "nenhum", "nome": "fundo"})
    C("retangulo", {"x": 5, "y": 5, "larg": 20, "alt": 20, "preench": "100K", "traco": "nenhum", "nome": "preto"})
    C("retangulo", {"x": 30, "y": 5, "larg": 20, "alt": 20, "preench": "0K", "traco": "nenhum", "nome": "branco"})
    C("elipse", {"x": 55, "y": 5, "larg": 20, "preench": "spot:PANTONE 286 C:100,75,0,0", "traco": "nenhum", "nome": "especial"})
    C("retangulo", {"x": 80, "y": 5, "larg": 15, "alt": 20, "preench": "#ff0000", "traco": "nenhum", "nome": "rgb"})
    T = lambda x, y: pg.evaluate("([x, y]) => VKN.cmd('tinta_em', {x, y})", [x, y])
    ok(T(15, 15)["K"] == 100 and T(15, 15)["Y"] == 0, f"preto sem sobreimpressão vaza o amarelo ({T(15, 15)})")
    C("alterar", {"nomes": ["preto", "branco"], "sobreimprimir": True})
    ok(T(15, 15)["K"] == 100 and T(15, 15)["Y"] == 100, f"preto sobreimpresso fica sobre o amarelo ({T(15, 15)})")
    ok(T(40, 15)["Y"] == 100, f"branco sobreimpresso some ({T(40, 15)})")
    t = T(65, 15)
    ok(t.get("PANTONE 286 C") == 100 and t["Y"] == 0, f"especial vaza o processo ({t})")
    t = T(87, 15)
    ok(t["M"] > 80 and t["Y"] > 80 and t["C"] < 10, f"RGB vira CMYK pelo perfil ({t})")
    r = C("separacoes", {"ativo": True})
    ok(r["ativo"] and len(r["tintas"]) == 5, f"prévia ligada com 4 + 1 especial ({[x['nome'] for x in r['tintas']]})")
    pg.wait_for_timeout(400)
    pg.locator("#vk").screenshot(path=os.path.join(SAI, "separacoes.png"))
    seps = pg.evaluate("c => VKN.cmd('exportar_separacoes', {caminho: c, ppi: 72})", os.path.join(SAI, "sep.png"))["arquivos"]
    ok(len(seps) == 4 and not any(x.endswith("_C.png") for x in seps) and all(os.path.isfile(x) for x in seps),
       f"exportar separações: só as chapas com tinta ({[os.path.basename(x) for x in seps]})")
    C("separacoes", {"ativo": False})

    print("vínculos")
    from PIL import Image as _Im
    v1, v2 = os.path.join(SAI, "vinc_a.png"), os.path.join(SAI, "vinc_b.png")
    _Im.new("RGB", (600, 400), (200, 30, 30)).save(v1); _Im.new("RGB", (300, 300), (30, 30, 200)).save(v2)
    C("novo", {"nome": "Vinc", "larg": 100, "alt": 60})
    im_ = C("imagem", {"arquivo": v1, "x": 5, "y": 5, "larg": 50})
    vs = C("vinculos")["vinculos"]; ok(len(vs) == 1 and vs[0]["estado"] == "ok" and vs[0]["usos"] == 1, f"vínculos: imagem colocada ok ({vs})")
    _Im.new("RGB", (600, 400), (30, 200, 30)).save(v1)
    ok(C("vinculos")["vinculos"][0]["estado"] == "mudou", "vínculos: original editado aparece como mudou")
    C("atualizar_vinculo"); ok(C("vinculos")["vinculos"][0]["estado"] == "ok", "atualizar_vinculo relê o original")
    larg0 = C("info", {"id": im_["id"]})[0]["caixa_mm"]["larg"]
    r_ = C("revincular", {"id": im_["id"], "arquivo": v2}); larg1 = C("info", {"id": im_["id"]})[0]["caixa_mm"]["larg"]
    ok(r_["w"] == 300 and abs((larg1 or 0) - (larg0 or 1)) < 0.1, f"revincular troca a imagem e mantém a largura ({larg0} → {larg1}, {r_})")
    vk_ = os.path.join(SAI, "vinc.aknv"); C("salvar", {"caminho": vk_}); pg.evaluate("c => VKN.abrir(c)", vk_); pg.wait_for_timeout(500); os.remove(v2)
    ok(C("vinculos")["vinculos"][0]["estado"] == "sem_original", "sem o original: fica a cópia incorporada (sem_original)")

    print("3D, retocar letra, documento de tela")
    C("novo", {"nome": "3D", "larg": 200, "alt": 120})
    pf = C("caminho", {"d": "M40 100 L60 100 L66 30 L67 28", "preench": "C2 M3 Y10 K0", "traco": "nenhum"})
    g3 = C("girar_3d", {"ids": [pf["id"]], "inclinar": 15, "material": "ceramica"})
    ok(pg.evaluate("id => vkObj(id).itens.filter(o => o.tipo === 'malha').length", g3["id"]) == 2, "girar_3d: frente e fundo em malha de degradê")
    lg = C("texto", {"conteudo": "LOGO", "x": 30, "y": 60, "fonte": "Arial", "estilo": "Bold", "tamanho": 20, "preench": "C0 M68 Y72 K0"}); C("contornos", {"ids": [lg["id"]]})
    arte_ = pg.evaluate("() => VK.doc.camadas[0].itens.filter(o => !o.tres_d).map(o => o.id)")
    C("mapear_arte", {"id3d": g3["id"], "arte": arte_, "y": 35})
    rot_ = pg.evaluate("id => !!vkObj(id).itens.find(o => o.nome === '3D rótulo')", g3["id"]); ok(rot_, "mapear_arte: rótulo recortado pela frente do copo")
    w0 = C("info", {"ids": [g3["id"]]})[0]["caixa_mm"]["larg"]; C("editar_3d", {"ids": [g3["id"]], "girar": 40, "inclinar": 30}); w1 = C("info", {"ids": [g3["id"]]})[0]["caixa_mm"]
    ok(pg.evaluate("id => vkObj(id).tres_d.mapas.length", g3["id"]) == 1 and w1["alt"] > 0, f"editar_3d refaz mantendo a arte mapeada ({w0} → {w1})")
    cx_ = C("retangulo", {"x": 120, "y": 40, "larg": 40, "alt": 50, "preench": "C100 M55 Y35 K45", "traco": "nenhum"})
    e3 = C("extrudar_3d", {"ids": [cx_["id"]], "profundidade": 15, "girar": -30, "inclinar": 15})
    ok(pg.evaluate("id => vkObj(id).itens.filter(o => o.nome === '3D lado').length", e3["id"]) == 2, "extrudar_3d: caixa mostra 2 laterais (topo e lado)")
    pdf3 = os.path.join(SAI, "3d.pdf"); r3 = C("exportar_pdf", {"caminho": pdf3, "padrao": "x1a", "forcar": True})
    ok(r3["verificado"], f"PDF/X-1a com 3D vetorial ({r3.get('problemas')})")
    t_ = C("texto", {"conteudo": "maré", "x": 10, "y": 110, "fonte": "Arial", "tamanho": 30})
    b0 = C("info", {"ids": [t_["id"]]})[0]["caixa_mm"]; C("retocar_letra", {"ids": [t_["id"]], "letra": 3, "rot": -30, "subir": 6}); pg.wait_for_timeout(300)
    b1 = C("info", {"ids": [t_["id"]]})[0]["caixa_mm"]
    ok(b1["alt"] > b0["alt"] + 1 and pg.evaluate("id => vkObj(id).tipo", t_["id"]) == "texto", f"retocar_letra gira/sobe a letra e o texto segue editável ({b0} → {b1})")
    C("novo", {"nome": "Tela", "larg": 320, "alt": 180, "destino": "tela"})
    ok(pg.evaluate("[VK.doc.sangria, vkPadraoDoc()]") == [0, "rgb"], "documento de tela: sem sangria, fechamento/PDF digitais")

    print("efeitos e Aparência na separação, Aparência em grupo, SVG")
    C("novo", {"nome": "Ef sep", "larg": 100, "alt": 60})
    r1 = C("retangulo", {"x": 10, "y": 10, "larg": 30, "alt": 20, "preench": "C0 M100 Y0 K0", "traco": "nenhum"})
    C("efeito", {"ids": [r1["id"]], "tipo": "sombra", "dx": 4, "dy": 4, "desfoque": 0.2, "opacidade": 100})
    t = T(42, 32); ok(t["K"] > 60 and t["M"] < 10, f"sombra entra na chapa K ({t})")
    r2 = C("retangulo", {"x": 60, "y": 10, "larg": 30, "alt": 20, "preench": "C0 M0 Y100 K0", "traco": "nenhum"})
    C("aparencia", {"ids": [r2["id"]], "tipo": "traco", "cor": "C100 M0 Y0 K0", "espessura": 3})
    t = T(59.5, 20); ok(t["C"] > 60, f"traço da Aparência entra na chapa C ({t})")
    m_ = C("retangulo", {"x": 10, "y": 38, "larg": 30, "alt": 20, "preench": "C100 M0 Y0 K0", "traco": "nenhum"}); C("criar_malha", {"ids": [m_["id"]], "clarear": 80})
    t1, t2 = T(25, 48), T(10.5, 38.5); ok(t1["C"] < 60 < t2["C"], f"malha de degradê na chapa C (centro {t1['C']}, canto {t2['C']})")
    e1 = C("elipse", {"x": 60, "y": 40, "larg": 10, "preench": "C0 M0 Y100 K0", "traco": "nenhum"}); e2 = C("elipse", {"x": 75, "y": 40, "larg": 10, "preench": "C0 M0 Y100 K0", "traco": "nenhum"})
    g_ = C("agrupar", {"ids": [e1["id"], e2["id"]]}); C("aparencia", {"ids": [g_["id"]], "tipo": "traco", "cor": "100K", "espessura": 2})
    ok(pg.evaluate("id => { const p = vkPinturas(vkObj(id)); return !!p && p.some(q => q.traco && q.traco.cor) }", g_["id"]), "Aparência em grupo: contorno no conjunto")
    t = T(59.7, 45); ok(t["K"] > 60, f"Aparência do grupo entra na chapa K ({t})")
    svg = os.path.join(SAI, "efeitos.svg"); C("exportar_svg", {"caminho": svg}); sv = open(svg, encoding="utf-8").read()
    ok("<filter" in sv and "feOffset" in sv and sv.count("stroke=") >= 2, "SVG com sombra em <filter> e contornos da Aparência")

    pg.evaluate("c => VKN.abrir(c)", aknv)
    pg.wait_for_timeout(600)
    pg.locator("#vk").screenshot(path=a.print)
    print("  print:", a.print)
    ok(not erros, f"sem erros de JS ({erros[:3]})")
print(json.dumps({"falhas": falhas}, ensure_ascii=False))
sys.exit(1 if falhas else 0)
